config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'
  resources :comments
  resources :users, except: [:new]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'articles#index'
  # get '/articles', to: 'articles#index'

  resources :articles
  resources :categories
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
  
  belongs_to :user, class_name: "User", foreign_key: "user_id"
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destory]
  def index
    @article = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    # ActionController::Parameters.permit_all_parameters = true
    # render plain: params[:article].inspect
    @article = Article.new(article_params)
    @article.user = User.find(session[:user_id])
    if @article.save
      flash[:success] = 'Article was successfully created.'
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:success] = 'Article was successfully updated.'
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    flash[:success] = 'Article was successfully deleted.'
    @article.destroy
    redirect_to articles_path, status: :see_other
  end

  def show
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:warning] = "You can only edit or delete your artcles"
      redirect_to root_path
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |f| %>
  <%= f.label :title, "Title" %> </br>
<%= f.text_field :title %> <br>
<% article.errors.full_messages_for(:title).each do |message| %>
  <div><%= message %></div>
<% end %> <br>
<%= f.label :description, "Description" %> </br>
<%= f.text_area :description, size: "70x5" %> <br>
<% article.errors.full_messages_for(:description).each do |message| %>
  <div><%= message %></div>
<% end %> <br>
<%= f.submit "Submit", disable_with: 'Submiting...' %>
<% end %>

app/views/articles/edit.html.erb
<h1>Update an article</h1>
<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<br>
<% if logged_in?  %>
  <%= link_to "Create new Article", new_article_path, class:"btn btn-primary p-1 m-2" %>
  <%= link_to "Signout",signout_path, data: { turbo_method: :delete }  %>
<% else %>
  <%= link_to "Signin", signin_path  %>
  <%= link_to "Signup", signup_path  %>
<% end %>
<br>
<ul>
  <% @article.each do |article| %>
    <li>
      <a href="<%= article_path(article) %>" class="btn btn-link">
        <%= article.title %>
      </a> : 
      <%= article.description %>
    </li>
  <% end %>
</ul>

app/views/articles/new.html.erb
<%= render 'shared/errors' , obj: @article %>
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.description %></p>
<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
  <ul class="list-group m-2">
    <li class="list-group-item"><%= link_to "Edit", edit_article_path(@article) %></li>
    <li class="list-group-item"><%= link_to "Destroy", @article,
                    data:{ turbo_method: :delete, turbo_confirm: "Are you sure?"}
                 %></li>
  </ul>
<% end %>
<%= link_to "Articles", articles_path %>